import type { Metadata } from 'next';
import AdminLayout from '@/components/Layouts/AdminLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AdminMainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div>
      <AdminLayout>{children}</AdminLayout>
    </div>
  );
}
