'use client';
import 'jsvectormap/dist/css/jsvectormap.css';
import 'flatpickr/dist/flatpickr.min.css';
import '@/css/satoshi.css';
import '@/css/style.css';
import React, { useEffect, useState } from 'react';
import Loader from '@/components/common/Loader';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
<<<<<<< HEAD
import AuthProvider from './provider';
const inter = Inter({ subsets: ['latin'] });
import TopBar from '@/components/pages/components/topBar/topBar';
export const metadata: Metadata = {
  title: 'Quản lý trẻ em học',
  description: 'Phần mềm quản lý trẻ em học',
};
=======
import 'tailwindcss/tailwind.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
>>>>>>> e919764 (commit Front end nhe iu)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [loading, setLoading] = useState<boolean>(true);

  // const pathname = usePathname();

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD
        <AuthProvider>
          <TopBar />
          {children}
        </AuthProvider>
=======
        <div className="dark:bg-boxdark-2 dark:text-bodydark">
          {loading ? <Loader /> : children}
        </div>
>>>>>>> e919764 (commit Front end nhe iu)
      </body>
    </html>
  );
}
