import type { Metadata } from 'next';
import { Providers } from '@/app/providers';
import { CookieGetInfo } from '@/backend/feature/validate';
import Footer from '@/components/Footer';
import Header from '@/components/Header/headerUser';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function MainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const userInfo = await CookieGetInfo();
  let userName: string | null = userInfo;
  if (userName != null) {
    userName = userInfo.name;
  }
  return (
    <div className="bg-[#FCFCFC] dark:bg-black">
      <Providers>
        <Header name={userName} />
        {children}
        <Footer />
      </Providers>
    </div>
  );
}
