import Sidebar from '@/app/admin/support/sidebar';
import type { Metadata } from 'next';
import { GetUserID } from '@/backend/feature/validate';

export const metadata: Metadata = {
  title: 'Quản lý ',
  description: 'Generated by create next app',
};

export default async function AdminMainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const userID = await GetUserID();
  return (
    <div className="bg-gray-900 flex h-[80wh]">
      {/* Sidebar */}
      <div className="bg-gray-800 w-4/12 p-4">
        <div className="text-lg font-bold ">
          <Sidebar userID={userID} />
        </div>
      </div>
      <div className="w-px bg-black dark:bg-white"></div>
      {/* Main Content */}
      <div className="bg-gray-900 w-8/12 p-4">{children}</div>
    </div>
  );
}
